In [61]:
import os
import pandas as pd

In [62]:
folder_path = '.'

# список для хранения датафреймов
dfs = []

for file_name in os.listdir(folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(folder_path, file_name)
        df = pd.read_csv(file_path)
        df['brand'] = file_name.split('.')[0]  # Добавление колонки с маркой машины
        dfs.append(df)

In [63]:
combined_df = pd.concat(dfs, ignore_index=True)
combined_df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,brand,tax(£),fuel type,engine size,mileage2,fuel type2,engine size2,reference
0,A1,2017.0,12500,Manual,15735,Petrol,150.0,55.4,1.4,audi,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A6,2016.0,16500,Automatic,36203,Diesel,20.0,64.2,2.0,audi,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A1,2016.0,11000,Manual,29946,Petrol,30.0,55.4,1.4,audi,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A4,2017.0,16800,Automatic,25952,Diesel,145.0,67.3,2.0,audi,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A3,2019.0,17300,Manual,1998,Petrol,145.0,49.6,1.0,audi,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118145,Eos,2012.0,5990,Manual,74000,Diesel,125.0,58.9,2.0,vw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118146,Fox,2008.0,1799,Manual,88102,Petrol,145.0,46.3,1.2,vw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118147,Fox,2009.0,1590,Manual,70000,Petrol,200.0,42.0,1.4,vw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118148,Fox,2006.0,1250,Manual,82704,Petrol,150.0,46.3,1.2,vw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118149,Fox,2007.0,2295,Manual,74000,Petrol,145.0,46.3,1.2,vw,NaN,NaN,NaN,NaN,NaN,NaN,NaN